# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GuestBook' do

pod 'Alamofire', '~> 4.0'
pod 'AlamofireObjectMapper'
pod 'AlamofireMapper'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

pod 'PusherSwift'

end
