# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GuestBook' do

pod 'Alamofire', '= 5.0.0-rc.2'
pod 'AlamofireObjectMapper'
pod 'AlamofireMapper'

end
